allapps/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import *


app_name = 'allapps'
handler404 = '.views.error_view'


urlpatterns = [
    url(r'^$', index_view, name="index"),
    url(r'^elaqe$', contactus_view, name="contact"),
    url(r'^haqqimizda$', aboutus_view, name="aboutus"),
    url(r'^xestelikler$', services_view, name="services"),
    url(r'^(?P<slug>.*)/$', illness_details, name='illness_details'),
    url(r'^gallery$', gallery_view, name='gallery'),
    ]

turkiyedecerrahiyye/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
# from home import views as  home_views
from django.conf.urls.i18n import i18n_patterns 


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]


urlpatterns += i18n_patterns(
    url(r'^', include('allapps.urls', namespace='allapps')),


)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Türkiyədə cərrahiyyə administrasiyası'
admin.site.site_title = 'Türkiyədə cərrahiyyə administrasiyası'
admin.site.index_title = 'Türkiyədə cərrahiyyə administrasiyası'

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Türkiyədə Cərrahiyyə | Sağlamlığa gedən yolda sizin bələdçiniz</title>
    
    <!--Favicons-->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    
    <!--Bootstrap and Other Vendors-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl.carousel/css/owl.carousel.min.css' %}">    
    <link rel="stylesheet" href="{% static 'vendors/owl.carousel/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/flexslider/flexslider.css' %}" media="screen">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/bootstrap-datepicker/css/datepicker3.css' %}" media="screen">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <!--Fonts-->

    <!--Mechanic Styles-->
    <link rel="stylesheet" href="{% static 'css/default/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive/responsive.css' %}">
    
    
</head>
<body class="default home">
    
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'allapps:index' %}"><img src="/static/images/logo/4.jpeg" style="width: 250px; height: 150px;" alt=""></a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_nav" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="book-appointment.html" class="navbar-toggle visible-xs" data-toggle="modal" data-target="#appointmefnt_form_pop">book appointment</a>
            </div>
            
            <!-- Collect the nav links, forms, and other content for toggling -->            
            <div class="collapse navbar-collapse" id="main_nav">                
                <ul class="nav navbar-nav navbar-right">
                    <li class="active dropdown">
                        <a href="{% url 'allapps:index' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{% trans 'Əsas səhİfə' %}</a>
                    </li>
                    <li class="dropdown">
                        <a href="{% url 'allapps:services' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{% trans 'Xəstəlİklər' %}</a>
                    </li>
                    <li>
                        <a href="{% url 'allapps:gallery' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{% trans 'Galereya' %}</a>
                    </li>
                    <li class="dropdown"><a class="dropdown-toggle" href="{% url 'allapps:aboutus' %}">{% trans "Haqqımızda" %}</a></li>
                    <li class="dropdown"><a class="dropdown-toggle" href="{% url 'allapps:contact' %}">{% trans "əlaqə" %}</a></li>
                    <li class="hidden-xs book"><a href="#" data-toggle="modal" data-target="#appointmefnt_form_pop">az</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% block body %}
{% endblock %}
     
    <footer class="row">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-6 col-lg-5 footer_menuList">
                    <div class="heading row m0"><img src="/static/images/logo/1.png" alt=""></div>
                    <div class="row menuList">
                      <p style="color: white;">{{ settings.about_text }}</p>
                    </div>
                </div>
                <div class="col-sm-4 col-md-6 col-lg-3 footer_menuList">
                    <h4 style="color: white">Menyu</h4>
                    <div class="row address m0">
                 <div class="row menuList">
                        <ul class="firstOrderList nav">
                            <li><a href="{% url 'allapps:index' %}">home</a></li>
                            <li><a href="{% url 'allapps:services' %}">xəstəlİklər</a></li>
                            <li><a href="{% url 'allapps:gallery' %}">Galereya</a></li>
                            <li><a href="/">Həkİmlər</a></li>
                            <li><a href="{% url 'allapps:contact' %}">Bİzİmlə Əlaqə</a></li>
                            <li><a href="{% url 'allapps:aboutus' %}">Haqqımızda</a></li>
                        </ul>
                    </div> 
                    </div>
                </div>
                <div style="color: white" class="col-sm-12 col-md-12 col-lg-4 footer_address">
                    <h4>Əlaqə</h4>
  
                        <div class="media address_line">
                            <div class="media-left icon"><i class="fa fa-envelope"></i></div>
                            <div class="media-body address_text">{{ settings.email }}</div>
                        </div>
                        <div class="media address_line">
                            <div class="media-left icon"><i class="fa fa-phone"></i></div>
                            <div class="media-body address_text">{{ settings.number }}</div>
                        </div>
                        <div class="media address_line">
                            <div class="media-left icon"><i class="fa fa-map-marker"></i></div>
                            <div class="media-body address_text">{{ settings.adress }}</div>
                        </div>


                </div>
            </div>
            <div class="row m0 footer_bottom">
                <ul class="list-inline social_menu m0 fleft">
                    <li><a href="{{ settings.twitter }}"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="{{ settings.facebook }}"><i class="fab fa-facebook"></i></a></li>
                    <li><a href="{{ settings.linkedin }}"><i class="fab fa-linkedin"></i></a></li>
                    <li><a href="{{ settings.pinterest }}"><i class="fab fa-pinterest"></i></a></li>
                    <li><a href="{{ settings.instagram }}"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="{{ settings.youtube }}"><i class="fab fa-youtube"></i></a></li>
                </ul>
                <div class="fright copyright">&copy; <a href="{% url 'allapps:index' %}">turkiyedecerrahiyye.az 2019</a>. {% trans 'Bütün hüquqları qorunur!' %}.</div>
            </div>
        </div>
    </footer>
  
    
    <!--jQuery, Bootstrap and other vendor JS-->
    
    <!--jQuery-->
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    
    <!--Bootstrap JS-->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    
    <!--Owl Carousel-->
    <script src="{% static 'vendors/owl.carousel/js/owl.carousel.min.js' %}"></script>
    
    <!--Counter Up-->
    <script src="{% static 'vendors/counterup/jquery.counterup.min.js' %}"></script>
    
    <!--Waypoints-->
    <script src="{% static 'vendors/waypoints/jquery.waypoints.min.js' %}"></script>
    
    <!--Bootstrap Date-->
    <script src="{% static 'vendors/bootstrap-datepicker/css/datepicker3.css' %}"></script>
    
    <!--FlexSlider-->
    <script src="{% static 'vendors/flexslider/jquery.flexslider-min.js' %}"></script>
    
    <!--Strella JS-->
    <script src="{% static 'js/theme.js' %}"></script>
</body>
</html>